server:
  port: 8889
spring:
  application:
    name: PDA_Test

  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    cache: false
    suffix: .html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB